-- Business Query 1
-- Total revenue generated by each product category

SELECT
    p.category,
    SUM(oi.subtotal) AS total_revenue
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.category
ORDER BY total_revenue DESC;


-- Business Query 2
-- Top 5 customers by total spending

SELECT
    c.first_name,
    c.last_name,
    SUM(o.total_amount) AS total_spent
FROM orders o
JOIN customers c ON o.customer_id = c.customer_id
GROUP BY c.customer_id, c.first_name, c.last_name
ORDER BY total_spent DESC
LIMIT 5;


-- Business Query 3
-- Monthly sales trend

SELECT
    YEAR(o.order_date) AS year,
    MONTH(o.order_date) AS month,
    SUM(o.total_amount) AS monthly_sales
FROM orders o
GROUP BY YEAR(o.order_date), MONTH(o.order_date)
ORDER BY year, month;


-- Business Query 4
-- Order count by status

SELECT
    status,
    COUNT(*) AS order_count
FROM orders
GROUP BY status;


-- Business Query 5
-- Average order value

SELECT
    ROUND(AVG(total_amount), 2) AS average_order_value
FROM orders;
